reddcoin:
    image: noobsmuc/reddcoin:latest
    container_name: reddcoin
    hostname: reddcoin
    environment:
       - PASSWORDPHRASE=11 22 33 44 55 66 77 88 99 1010 1111 1212
       - SLEEPNUMBERANDSUFFIX=20m
    volumes:
      - "E:/reddcoinChain:/root/.reddcoin"